site_name: "Varbase Recipes"
repo_url: https://git.drupalcode.org/project/varbase_recipes
repo_name: drupal/varbase_recipes
edit_uri: /-/edit/1.0.x/docs/

theme:
  name: material
  language: en
  logo: logo.png
  # favicon: favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand

nav:
  - Introduction: "index.md"
  - Config Actions:
      - setCKEditorMediaEmbedVersion: "config-actions/set-ckeditor-media-embed-version.md"
      - mergeAllowedHtml: "config-actions/merge-allowed-html.md"
      - enableCKEditorPlugin: "config-actions/enable-ckeditor-plugin.md"
      - addButtonPluginIntoActiveToolbar: "config-actions/add-button-plugin-into-active-toolbar.md"
      - updatePluginSettings: "config-actions/update-plugin-settings.md"
      - setEntityReferenceHandler: "config-actions/set-entity-reference-handler.md"
      - setAiContextItemsDefaultScope: "config-actions/set-ai-context-items-default-scope.md"

plugins:
  - search
  - privacy:
      enabled: !ENV [CI, false]

markdown_extensions:
  # - markdown.extensions.admonition
  - pymdownx.extra
